import {
  SiApple,
  SiDiscord,
  SiDropbox,
  SiFacebook,
  SiGithub,
  SiGitlab,
  SiGoogle,
  SiKick,
  SiReddit,
  SiRoblox,
  SiSpotify,
  SiTiktok,
  SiTwitch,
  SiVk,
  SiX,
  SiZoom,
} from "@icons-pack/react-simple-icons";
import { SSOProviderType } from "jazz-react-auth-betterauth";

export const ssoIcons: Record<SSOProviderType, React.ReactNode> = {
  github: <SiGithub />,
  google: <SiGoogle />,
  apple: <SiApple />,
  discord: <SiDiscord />,
  facebook: <SiFacebook />,
  microsoft: undefined,
  twitter: <SiX />,
  dropbox: <SiDropbox />,
  linkedin: undefined,
  gitlab: <SiGitlab />,
  kick: <SiKick />,
  tiktok: <SiTiktok />,
  twitch: <SiTwitch />,
  vk: <SiVk />,
  zoom: <SiZoom />,
  roblox: <SiRoblox />,
  reddit: <SiReddit />,
  spotify: <SiSpotify />,
};
