name: Playwright Tests

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    timeout-minutes: 60
    runs-on: blacksmith-4vcpu-ubuntu-2204
    continue-on-error: true
    strategy:
      matrix:
        project: ["tests/e2e", "examples/chat",  "examples/clerk", "examples/betterauth", "examples/file-share-svelte", "examples/form", "examples/jazz-nextjs", "examples/music-player", "examples/organization", "examples/pets", "starters/react-passkey-auth"]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Source Code
        uses: ./.github/actions/source-code/

      - name: Pnpm Build
        run: pnpm turbo build
        working-directory: ./${{ matrix.project }}

      - name: Install Playwright Browsers
        run: pnpm exec playwright install
        working-directory: ./${{ matrix.project }}

      - name: Run Playwright tests
        run: pnpm exec playwright test
        working-directory: ./${{ matrix.project }}

      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: ${{ hashFiles(format('{0}/package.json', matrix.project)) }}-playwright-report
          path: ./${{ matrix.project }}/playwright-report/
          retention-days: 30
